Repository zeroeightysix/KAMI, pull requests merged in 2020-09, with the labels that each got.

#228 Baritone integration
  build.gradle.kts
  src/main/java/me/zeroeightsix/kami/feature/module/player/AutoWalk.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinClientPlayerEntity.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinComeCommand.java
  src/main/java/me/zeroeightsix/kami/mixin/client/MixinLivingEntity.java
  src/main/kotlin/me/zeroeightsix/kami/Integration.kt
  src/main/kotlin/me/zeroeightsix/kami/Utils.kt
  src/main/kotlin/me/zeroeightsix/kami/event/Events.kt
  src/main/kotlin/me/zeroeightsix/kami/feature/module/Freecam.kt
  src/main/kotlin/me/zeroeightsix/kami/feature/module/NoSlowDown.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/MenuBar.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/widgets/ActiveModules.kt
  src/main/kotlin/me/zeroeightsix/kami/setting/KamiConfig.kt
  src/main/resources/fabric.mod.json
  src/main/resources/kami.mixins.json
Labels: enhancement, help wanted

#229 Added Discord RPC Module
  build.gradle.kts
  src/main/java/me/zeroeightsix/kami/mixin/client/IBackedConfigLeaf.java
  src/main/kotlin/me/zeroeightsix/kami/Utils.kt
  src/main/kotlin/me/zeroeightsix/kami/feature/module/DiscordStatus.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/text/CompiledText.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/text/VarMap.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/widgets/ActiveModules.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/widgets/Coordinates.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/widgets/GraphPinnableWidget.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/widgets/Information.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/widgets/TextPinnableWidget.kt
  src/main/kotlin/me/zeroeightsix/kami/gui/windows/modules/Modules.kt
  src/main/kotlin/me/zeroeightsix/kami/setting/KamiConfig.kt
Labels: enhancement

#144 added FastExp
  src/main/java/me/zeroeightsix/kami/module/modules/player/FastExp.java
Labels: enhancement

#230 Create MurderMysteries.kt
  src/main/kotlin/me/zeroeightsix/kami/feature/module/MurderMysteries.kt
Labels: enhancement

#153 AutoReplenish
  src/main/java/me/zeroeightsix/kami/module/modules/player/AutoReplenish.java
Labels: enhancement

#161 Chat AntiSpam
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AntiSpam.java
Labels: enhancement

#163 VisualRange
  src/main/java/me/zeroeightsix/kami/module/modules/misc/VisualRange.java
Labels: enhancement

#164 AutoSpawner
  src/main/java/me/zeroeightsix/kami/module/modules/misc/AutoSpawner.java
Labels: enhancement, needs testing

#243 Added say Command
  src/main/kotlin/me/zeroeightsix/kami/feature/command/SayCommand.kt
Labels: enhancement
